name: appmarenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cfgrib
  - python=3.7
  - gdal
  - wxpython
  - numpy
  - matplotlib=3.2
  - scipy
  - xarray
  - pandas
  - cartopy
  - scikit-learn
  - kneed
